version: "0.5"

processes:
  solr:
    command: "solr start -Dsolr.environment=${SOLR_ENV} -p $SOLR_PORT"
    is_daemon: true
    shutdown:
      command: "solr stop -p $SOLR_PORT"
    availability:
      restart: "always"
    readiness_probe:
      exec:
        command: "curl -qsf http://localhost:$SOLR_PORT/solr"
