name: Test the debox solr plugin
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.11.0
        with:
          project-path: './test'
      - name: Run the test script
        working-directory: test
        run: devbox run test
